### ISSUE TITLE
Question on Claude secret setting

### ISSUE THREAD

**Issue by agalloch** [gsamokovarov/claude#1]
Hello, this may not be an issue but rather an intended behaviour so, please,:bear: with me :)

Recently I've noticed that Rails' extension for `claude` transforms the passed secret with `inspect`:
https://github.com/gsamokovarov/claude/blob/14cabc350733160a0d9fa1265b5610564bfd41a4/lib/claude/extensions.rb#L43

As in my Rails console this transformation is not an identity:
```
[16] pry(main)> Claude.secret
=> "85n668n5...." # omitted for brevity
[17] pry(main)> Claude.secret == Claude.secret.inspect
=> false
```
I was wondering if this is actually a bug?

Thank you in advance!

**Comment by gsamokovarov** [comment]
The extension attribute methods are defined in a class eval that is given a string to be interpreted as Ruby code. The inspect is here, so it results in a `"string literal"` in the Ruby string:

See a few lines below of 👇:

https://github.com/gsamokovarov/claude/blob/14cabc350733160a0d9fa1265b5610564bfd41a4/lib/claude/extensions.rb#L52

E.g. the generated code that is later on eval'd looks like:

```ruby
cipher = Cipher.for_decryption("80fe8946b...", encrypted_pin_iv)
```

Instead of the code below, which won't compile:

```ruby
cipher = Cipher.for_decryption(80fe8946b..., encrypted_pin_iv)
```

**Comment by agalloch** [comment]
Just as a mind exercise, in case one doesn't want to rely on `string.inspect` (for various reasons), would the following approach be equivalent:
```diff
-attr_secret   = options.fetch(:secret, Claude.secret).inspect 
+attr_secret   = options.fetch(:secret, Claude.secret)

# and then

-cipher = Cipher.for_decryption(#{attr_secret}, #{attr_iv})
+cipher = Cipher.for_decryption("#{attr_secret}", #{attr_iv})

-cipher = Cipher.for_encryption(#{attr_secret}, iv)
+cipher = Cipher.for_encryption("#{attr_secret}", iv)
```
or it would again not "compile"? :slightly_smiling_face:

**Comment by gsamokovarov** [comment]
This can work as well. 👍
